version: "3.9"
services:
  postgresql-9.5.23-plv8-2.1.2:
    build: postgresql-9.5.23-plv8-2.1.2

  postgresql-9.6.9-plv8-2.1.2:
    build: postgresql-9.6.9-plv8-2.1.2

  postgresql-9.6.10-plv8-2.1.2:
    build: postgresql-9.6.10-plv8-2.1.2

  postgresql-9.6.11-plv8-2.1.2:
    build: postgresql-9.6.11-plv8-2.1.2

  postgresql-9.6.12-plv8-2.1.2:
    build: postgresql-9.6.12-plv8-2.1.2

  postgresql-9.6.13-plv8-2.1.2:
    build: postgresql-9.6.13-plv8-2.1.2

  postgresql-9.6.14-plv8-2.1.2:
    build: postgresql-9.6.14-plv8-2.1.2

  postgresql-9.6.15-plv8-2.1.2:
    build: postgresql-9.6.15-plv8-2.1.2

  postgresql-9.6.16-plv8-2.1.2:
    build: postgresql-9.6.16-plv8-2.1.2

  postgresql-9.6.17-plv8-2.1.2:
    build: postgresql-9.6.17-plv8-2.1.2

  postgresql-9.6.18-plv8-2.1.2:
    build: postgresql-9.6.18-plv8-2.1.2

  postgresql-9.6.19-plv8-2.1.2:
    build: postgresql-9.6.19-plv8-2.1.2

  postgresql-9.6.20-plv8-2.1.2:
    build: postgresql-9.6.20-plv8-2.1.2
